# Generated by Django 3.1.7 on 2021-03-16 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shops',
            new_name='Shop',
        ),
    ]
