# Generated by Django 3.1.7 on 2021-03-30 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0004_auto_20210319_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='myproduct',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Myproduct',
        ),
    ]
